### ISSUE TITLE
unable to run examples

### ISSUE THREAD

**Issue by trondhindenes** [influxdata/jaeger-influxdb#6]
Whatever I try to do, I get this:
019-07-03T19:19:54.749Z [DEBUG] jaeger-influxdb-linux: 2019-07-03T19:19:54.748Z [ERROR] jaeger-influxdb: failed to open store: error="missing flags; for InfluxDB V1 set database and retention policy; for InfluxDB V2 set organization, bucket and token"

The readme doesn't contain any info about how to set retention policy, for example. The "regular" jaeger images support running with `--help` to print all options, but these images seem to not support that (`docker run quay.io/influxdb/jaeger-collector-influxdb --help` just errors out) 

Tried building a docker-based stack based on public images and also a modified version of the docker-compose file based on images on quay.io. Not getting anywhere.

```yaml
version: "3.7"

networks:
  net-test:

services:
  influxdb:
    image: docker.io/influxdb:1.7
    container_name: influxdb
    hostname: influxdb
    environment:
      INFLUXDB_DB: tracing
    ports:
      - "8086:8086" # HTTP service
    networks:
      - net-test


  jaeger-collector:
    image: quay.io/influxdb/jaeger-collector-influxdb
    container_name: jaeger-collector
    depends_on:
      - influxdb
    ports:
      - "14267:14267" # TCP, spans from jaeger-agent
    networks:
      - net-test
    command: >
      /bin/sh -c "
        while ! nc -z influxdb 8086;
        do
          echo waiting for influxdb;
          sleep 1;
        done;
        /go/bin/collector-linux
      "

  jaeger-query:
    image: quay.io/influxdb/jaeger-query-influxdb
    container_name: jaeger-query
    depends_on:
      - influxdb
    ports:
      - "8182:16686" # HTTP UI
    networks:
      - net-test
    command: >
      /bin/sh -c "
        while ! nc -z influxdb 8086;
        do
          echo waiting for influxdb;
          sleep 1;
        done;
        /go/bin/query-linux
      "

```

**Comment by rawkode** [comment]
Checkout my docker-compose file for an example:

https://github.com/rawkode/distributed-calculator/blob/master/docker-compose.yml

**Comment by wholegroup** [comment]
@trondhindenes You should set up environment variables INFLUXDB_HOST and INFLUXDB_DATABASE as well.

as an example:
```
version: '3.7'

services:
  jaeger-influxdb:
    container_name: jaeger-influxdb
    image: docker.io/influxdb:1.7
    environment:
      INFLUXDB_DB: tracing
    ports:
      - "8086" # HTTP service
    restart: on-failure
    networks:
      - net-jaeger

  jaeger-influxdb-scheme:
    container_name: jaeger-influxdb-scheme
    image: docker.io/influxdb:1.7
    command: >
          /bin/sh -c "
           sleep 20;
           influx -host jaeger-influxdb -execute 'CREATE RETENTION POLICY tracing ON tracing DURATION 7d REPLICATION 1'
          "
    depends_on:
      - jaeger-influxdb
    networks:
      - net-jaeger

  jaeger-collector:
    container_name: jaeger-collector
    build: collector/.
    image: jaeger-collector-influxdb-with-config
    command: ["--sampling.strategies-file=/config/strategies.json", "--log-level=debug"]
    depends_on:
      - jaeger-influxdb
    ports:
      - "14269" # metrics
#      - "14268:14268" # accept jaeger.thrift directly from clients
      - "14267:14267"
      - "14250" # accept model.proto
#      - "9411:9411" # zipkin
    restart: on-failure
    environment:
      INFLUXDB_HOST: http://jaeger-influxdb:8086
      INFLUXDB_DATABASE: tracing
      INFLUXDB_RETENTION_POLICY: tracing
    networks:
      - net-jaeger

  jaeger-query:
    container_name: jaeger-query
    image: quay.io/influxdb/jaeger-query-influxdb
    depends_on:
      - jaeger-influxdb
    ports:
      - "16686:16686" # HTTP UI
    networks:
      - net-jaeger
    restart: on-failure
    environment:
      INFLUXDB_HOST: http://jaeger-influxdb:8086
      INFLUXDB_DATABASE: tracing
      INFLUXDB_RETENTION_POLICY: tracing

  jaeger-agent:
    container_name: jaeger-agent
    image: jaegertracing/jaeger-agent
    command: ["--reporter.grpc.host-port=jaeger-collector:14250", "--log-level=debug"]
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "14271:14271" # http admin port to see /metrics
    restart: on-failure
    depends_on:
      - jaeger-collector
    networks:
      - net-jaeger

networks:
  net-jaeger:
```

I use a custom  `jaeger-collector` image to change default sampling strategy. You can just use `quay.io/influxdb/jaeger-collector-influxdb`

Also pls pay attention to `jaeger-influxdb-scheme` that create a retention policy if don't want to use default.
